app:
  version: 1.0.0

server:
  port: 8080

# log4j2
logging:
  level:
    org.springframework: DEBUG
    springfox: DEBUG
    org.springframework.data.redis: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.postgresql: DEBUG

spring:
  datasource:
    # Supabase Direct Connection mode
#    url: jdbc:postgresql://db.mdtcnsxevtlouxilvisn.supabase.co:5432/postgres
#    username: postgres
#    password: LUOCANYUlcy20000506YukiRinLL

    # Supabase Transaction Pooler mode
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
    username: postgres.mdtcnsxevtlouxilvisn
    password: LUOCANYUlcy20000506YukiRinLL

    # Supabase Session pooler mode
#    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?pgbouncer=true&connection_limit=1
#    username: postgres.mdtcnsxevtlouxilvisn
#    password: LUOCANYUlcy20000506YukiRinLL
#    driver-class-name: org.postgresql.Driver

    hikari:
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: SupabasePool

      maximum-pool-size: 20
      minimum-idle: 10
      data-source-properties:
        # 禁用 HikariCP 的预编译语句缓存
        preparedStatementCacheQueries: 0
        preparedStatementCacheSizeMiB: 0
        prepareThreshold: 0  # Disable prepared statement caching

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
        bytecode:
          provider: bytebuddy
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  # E-mail (QQ 邮箱配置)
  mail:
    host: smtp.qq.com
    port: 465
    username: 3146672611@qq.com
    password: aecgjhbyertddcfe
    from:
      name: Phantoms Official
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
  data:
    # Redis
    redis:
      # Redis
      # Render Internal Redis URL
#      url: redis://red-d03imhre5dus73ab817g:6379
      # External Redis URL
      url: rediss://red-d03imhre5dus73ab817g:OXtvQrLbJ1WXXdjXMEVknm1hPnW8XFAo@oregon-keyvalue.render.com:6379

# swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      jdbc: true

#Napcat QQ
shiro:
  ws:
    server:
      enable: true
      url: "/ws"

xivapi:
  base-url: "https://v2.xivapi.com/api"


leancloud:
  app-id: "4NeSS81j4KK0uyYULpfk52yh-gzGzoHsz"
  app-key: "1xNZMz1XUVSLDTAv3XoVBgni"
  server-url: "https://4ness81j.lc-cn-n1-shared.com"
  # 开启 LeanCloud SDK 调试日志
  log-level: "DEBUG"

d1:
  api-url: https://api.cloudflare.com
  account-id: 0e7f3f296b75e9770c65d0d0fa73d7d7
  database-id: 0ad9906c-ec63-4111-b741-647627eee096
  api-token: XfJvEzGOKAMIn18NRE5MvkqU4C64s_ic3iNXRk1y
  log-level: WARNING